/**
 * WCAG 2.2 success criteria catalog (W3C Recommendation).
 * Summaries are concise operator-facing notes — not a substitute for the official spec.
 * Spec: https://www.w3.org/TR/WCAG22/
 */

export type WcagLevel = "A" | "AA" | "AAA";
export type WcagPrinciple = "1 Perceivable" | "2 Operable" | "3 Understandable" | "4 Robust";

export type Wcag22Criterion = {
  id: string;
  name: string;
  level: WcagLevel;
  principle: WcagPrinciple;
  /** Short “what to do” */
  intent: string;
  /** How it typically fails */
  failsWhen: string;
  /** Control Room / product relevance */
  productNote: string;
  /** New or changed emphasis in 2.2 vs 2.1 where notable */
  wcag22Note?: string;
};

export const WCAG22_CRITERIA: Wcag22Criterion[] = [
  // —— 1 Perceivable ——
  {
    id: "1.1.1",
    name: "Non-text Content",
    level: "A",
    principle: "1 Perceivable",
    intent: "Provide text alternatives for non-text content (images, icons, controls, CAPTCHA alternatives).",
    failsWhen: "Meaningful images lack alt; icon buttons have no accessible name; decorative images not marked empty/hidden.",
    productNote: "Every icon-only control needs aria-label or visible text.",
  },
  {
    id: "1.2.1",
    name: "Audio-only and Video-only (Prerecorded)",
    level: "A",
    principle: "1 Perceivable",
    intent: "Prerecorded audio-only → transcript; video-only → transcript or audio description track alternative.",
    failsWhen: "Podcasts/videos with no text or equivalent alternative.",
    productNote: "N/A unless Control Room embeds media.",
  },
  {
    id: "1.2.2",
    name: "Captions (Prerecorded)",
    level: "A",
    principle: "1 Perceivable",
    intent: "Captions for prerecorded synchronized media.",
    failsWhen: "Video with speech/dialogue and no captions.",
    productNote: "Required for marketing/tutorial video.",
  },
  {
    id: "1.2.3",
    name: "Audio Description or Media Alternative (Prerecorded)",
    level: "A",
    principle: "1 Perceivable",
    intent: "AD or full text alternative for prerecorded video with important visuals.",
    failsWhen: "Visual-only plot points never described.",
    productNote: "Use when shipping product demos with on-screen UI only.",
  },
  {
    id: "1.2.4",
    name: "Captions (Live)",
    level: "AA",
    principle: "1 Perceivable",
    intent: "Captions for live synchronized media.",
    failsWhen: "Live streams without captions where required.",
    productNote: "Live ops streams need caption pipeline if offered.",
  },
  {
    id: "1.2.5",
    name: "Audio Description (Prerecorded)",
    level: "AA",
    principle: "1 Perceivable",
    intent: "Audio description for prerecorded video.",
    failsWhen: "No AD when visuals convey unique info.",
    productNote: "AA bar for polished product video.",
  },
  {
    id: "1.2.6",
    name: "Sign Language (Prerecorded)",
    level: "AAA",
    principle: "1 Perceivable",
    intent: "Sign language interpretation for prerecorded audio content in media.",
    failsWhen: "No sign track when AAA claimed.",
    productNote: "AAA — rare unless specialized media product.",
  },
  {
    id: "1.2.7",
    name: "Extended Audio Description (Prerecorded)",
    level: "AAA",
    principle: "1 Perceivable",
    intent: "Extended AD when pauses in audio are insufficient.",
    failsWhen: "Dense visuals with no extended AD under AAA.",
    productNote: "AAA media production.",
  },
  {
    id: "1.2.8",
    name: "Media Alternative (Prerecorded)",
    level: "AAA",
    principle: "1 Perceivable",
    intent: "Full text alternative for synchronized media.",
    failsWhen: "No complete alternative under AAA.",
    productNote: "AAA.",
  },
  {
    id: "1.2.9",
    name: "Audio-only (Live)",
    level: "AAA",
    principle: "1 Perceivable",
    intent: "Live audio-only content has text alternative (e.g. captions/transcripts).",
    failsWhen: "Live audio without text alternative under AAA.",
    productNote: "AAA.",
  },
  {
    id: "1.3.1",
    name: "Info and Relationships",
    level: "A",
    principle: "1 Perceivable",
    intent: "Structure and relationships conveyed through presentation can be programmatically determined (headings, lists, tables, labels).",
    failsWhen: "Fake headings with bold only; tables for layout with no headers; unlabeled form groups.",
    productNote: "Use real h1–h3, lists, table headers, label/field associations.",
  },
  {
    id: "1.3.2",
    name: "Meaningful Sequence",
    level: "A",
    principle: "1 Perceivable",
    intent: "Reading order matches meaning when CSS/DOM order diverges.",
    failsWhen: "Visual order differs from DOM/tab/screen-reader order.",
    productNote: "Avoid CSS reordering that breaks board/log reading order.",
  },
  {
    id: "1.3.3",
    name: "Sensory Characteristics",
    level: "A",
    principle: "1 Perceivable",
    intent: "Instructions don’t rely only on shape, color, size, location, or sound.",
    failsWhen: "“Click the red button on the right” as only cue.",
    productNote: "Pair color status with text (DONE, DEFERRED).",
  },
  {
    id: "1.3.4",
    name: "Orientation",
    level: "AA",
    principle: "1 Perceivable",
    intent: "Content not locked to one display orientation unless essential.",
    failsWhen: "App forces landscape/portrait only without essential reason.",
    productNote: "Responsive Control Room should work portrait and landscape.",
  },
  {
    id: "1.3.5",
    name: "Identify Input Purpose",
    level: "AA",
    principle: "1 Perceivable",
    intent: "Autofill-capable inputs expose purpose (autocomplete tokens).",
    failsWhen: "Name/email/etc. fields without autocomplete where applicable.",
    productNote: "Use autocomplete on account/settings forms when added.",
  },
  {
    id: "1.3.6",
    name: "Identify Purpose",
    level: "AAA",
    principle: "1 Perceivable",
    intent: "Purpose of UI components, icons, regions can be programmatically determined (often via semantics/metadata).",
    failsWhen: "Custom icons/regions with no machine-readable purpose under AAA.",
    productNote: "AAA — landmarks + consistent naming help.",
  },
  {
    id: "1.4.1",
    name: "Use of Color",
    level: "A",
    principle: "1 Perceivable",
    intent: "Color is not the only means to convey information.",
    failsWhen: "Status only shown as green/red dots with no text/icon difference.",
    productNote: "Status text + icons alongside color tokens.",
  },
  {
    id: "1.4.2",
    name: "Audio Control",
    level: "A",
    principle: "1 Perceivable",
    intent: "Auto-playing audio >3s can be paused/stopped or volume controlled independently.",
    failsWhen: "Autoplay audio without stop control.",
    productNote: "Avoid autoplay audio in Control Room.",
  },
  {
    id: "1.4.3",
    name: "Contrast (Minimum)",
    level: "AA",
    principle: "1 Perceivable",
    intent: "Text contrast ≥ 4.5:1 (normal) or ≥ 3:1 (large text).",
    failsWhen: "Muted gray on dark surfaces below ratio.",
    productNote: "Check --color-muted on --color-surface; fix tokens if short.",
  },
  {
    id: "1.4.4",
    name: "Resize Text",
    level: "AA",
    principle: "1 Perceivable",
    intent: "Text resizable to 200% without loss of content/functionality (no horizontal scrolling for text, with exceptions).",
    failsWhen: "Fixed px containers clip text at 200% zoom.",
    productNote: "Prefer rem/clamp; avoid fixed-height text boxes that clip.",
  },
  {
    id: "1.4.5",
    name: "Images of Text",
    level: "AA",
    principle: "1 Perceivable",
    intent: "Use real text rather than images of text (except essential/customizable).",
    failsWhen: "PNG headlines as sole text content.",
    productNote: "UI copy is HTML/CSS text.",
  },
  {
    id: "1.4.6",
    name: "Contrast (Enhanced)",
    level: "AAA",
    principle: "1 Perceivable",
    intent: "Text contrast ≥ 7:1 (normal) or ≥ 4.5:1 (large).",
    failsWhen: "AA passes but AAA fails.",
    productNote: "AAA stretch goal for body copy.",
  },
  {
    id: "1.4.7",
    name: "Low or No Background Audio",
    level: "AAA",
    principle: "1 Perceivable",
    intent: "Background audio in speech content is low/none or controllable.",
    failsWhen: "Loud bed under speech under AAA.",
    productNote: "AAA media.",
  },
  {
    id: "1.4.8",
    name: "Visual Presentation",
    level: "AAA",
    principle: "1 Perceivable",
    intent: "User control of foreground/background, width, line spacing, text spacing; no full justification issues, etc.",
    failsWhen: "Rigid typography blocks user restyling under AAA.",
    productNote: "AAA reading comfort.",
  },
  {
    id: "1.4.9",
    name: "Images of Text (No Exception)",
    level: "AAA",
    principle: "1 Perceivable",
    intent: "Images of text only for pure decoration or essential presentation.",
    failsWhen: "Text-as-image used for branding under AAA claim.",
    productNote: "AAA.",
  },
  {
    id: "1.4.10",
    name: "Reflow",
    level: "AA",
    principle: "1 Perceivable",
    intent: "Content reflows at 320 CSS px width without two-dimensional scrolling (except some content types).",
    failsWhen: "Horizontal scroll required for main text/UI at mobile width.",
    productNote: "Mobile ~390px Control Room must not need horizontal scroll.",
  },
  {
    id: "1.4.11",
    name: "Non-text Contrast",
    level: "AA",
    principle: "1 Perceivable",
    intent: "UI components and graphical objects ≥ 3:1 against adjacent colors.",
    failsWhen: "Low-contrast borders on inputs; icon-only state indicators too faint.",
    productNote: "Borders, focus rings, chart lines need ≥ 3:1.",
  },
  {
    id: "1.4.12",
    name: "Text Spacing",
    level: "AA",
    principle: "1 Perceivable",
    intent: "No loss of content when user overrides line height, paragraph/letter/word spacing to set metrics.",
    failsWhen: "Fixed-height cards clip when spacing increases.",
    productNote: "Avoid overflow:hidden on text blocks without expansion room.",
  },
  {
    id: "1.4.13",
    name: "Content on Hover or Focus",
    level: "AA",
    principle: "1 Perceivable",
    intent: "Hover/focus popups are dismissible, hoverable, and persistent until dismissed/focus moves.",
    failsWhen: "Tooltip vanishes before it can be reached; no Esc dismiss.",
    productNote: "Tooltips/menus must be operable and dismissible.",
  },

  // —— 2 Operable ——
  {
    id: "2.1.1",
    name: "Keyboard",
    level: "A",
    principle: "2 Operable",
    intent: "All functionality available via keyboard (with exceptions for path-dependent input).",
    failsWhen: "Click-only controls; custom widgets not keyboard operable.",
    productNote: "Shortcuts + full tab access to Step, Scout, dialogs.",
  },
  {
    id: "2.1.2",
    name: "No Keyboard Trap",
    level: "A",
    principle: "2 Operable",
    intent: "Keyboard focus can move away from any component.",
    failsWhen: "Modal traps focus with no Esc/close path.",
    productNote: "Artifact & help overlays: Esc + close control.",
  },
  {
    id: "2.1.3",
    name: "Keyboard (No Exception)",
    level: "AAA",
    principle: "2 Operable",
    intent: "All functionality keyboard-operable with no exceptions.",
    failsWhen: "Any pointer-only path under AAA.",
    productNote: "AAA.",
  },
  {
    id: "2.1.4",
    name: "Character Key Shortcuts",
    level: "A",
    principle: "2 Operable",
    intent: "Single-character shortcuts can be turned off, remapped, or only active on focus.",
    failsWhen: "Global single-key shortcuts conflict with AT/speech and can’t be disabled.",
    productNote: "S/A/L/E/F shortcuts: document + ignore when typing; consider settings toggle.",
    wcag22Note: "Critical for apps with hotkeys like this Control Room.",
  },
  {
    id: "2.2.1",
    name: "Timing Adjustable",
    level: "A",
    principle: "2 Operable",
    intent: "Time limits can be turned off, adjusted, or extended (with exceptions).",
    failsWhen: "Session timeout with no warning/extend.",
    productNote: "Auto-run is user-controlled (Space); no forced timeouts.",
  },
  {
    id: "2.2.2",
    name: "Pause, Stop, Hide",
    level: "A",
    principle: "2 Operable",
    intent: "Moving/blinking/scrolling/auto-updating info can be paused/stopped/hidden.",
    failsWhen: "Infinite carousels/animations without pause.",
    productNote: "Auto-run pause; respect prefers-reduced-motion.",
  },
  {
    id: "2.2.3",
    name: "No Timing",
    level: "AAA",
    principle: "2 Operable",
    intent: "No timing essential to activity (except real-time events).",
    failsWhen: "Timed tests only under AAA claim.",
    productNote: "AAA.",
  },
  {
    id: "2.2.4",
    name: "Interruptions",
    level: "AAA",
    principle: "2 Operable",
    intent: "Interruptions can be postponed or suppressed (except emergencies).",
    failsWhen: "Unstoppable toast storms under AAA.",
    productNote: "Toasts toggle in Settings helps.",
  },
  {
    id: "2.2.5",
    name: "Re-authenticating",
    level: "AAA",
    principle: "2 Operable",
    intent: "Data preserved when re-authenticating after a session expires.",
    failsWhen: "Form data lost on re-login under AAA.",
    productNote: "Local run persistence already reduces loss.",
  },
  {
    id: "2.2.6",
    name: "Timeouts",
    level: "AAA",
    principle: "2 Operable",
    intent: "Users warned of timeouts that cause data loss.",
    failsWhen: "Silent data loss on timeout under AAA.",
    productNote: "AAA.",
  },
  {
    id: "2.3.1",
    name: "Three Flashes or Below Threshold",
    level: "A",
    principle: "2 Operable",
    intent: "Nothing flashes more than three times/sec (or is below general flash thresholds).",
    failsWhen: "Strobe/flashing ads or effects.",
    productNote: "No flashing UI; use subtle pulse sparingly.",
  },
  {
    id: "2.3.2",
    name: "Three Flashes",
    level: "AAA",
    principle: "2 Operable",
    intent: "No content flashes more than three times/sec.",
    failsWhen: "Any >3Hz flash under AAA.",
    productNote: "AAA stricter than 2.3.1.",
  },
  {
    id: "2.3.3",
    name: "Animation from Interactions",
    level: "AAA",
    principle: "2 Operable",
    intent: "Motion animation triggered by interaction can be disabled.",
    failsWhen: "Parallax/motion required with no reduce option under AAA.",
    productNote: "Honor prefers-reduced-motion.",
  },
  {
    id: "2.4.1",
    name: "Bypass Blocks",
    level: "A",
    principle: "2 Operable",
    intent: "Skip links or landmarks to bypass repeated blocks.",
    failsWhen: "No way to skip sticky header/nav.",
    productNote: "Add skip-to-main; use landmarks/sections.",
  },
  {
    id: "2.4.2",
    name: "Page Titled",
    level: "A",
    principle: "2 Operable",
    intent: "Descriptive document title.",
    failsWhen: "Empty or generic “App” title.",
    productNote: "Title: LVL Agent Control Room.",
  },
  {
    id: "2.4.3",
    name: "Focus Order",
    level: "A",
    principle: "2 Operable",
    intent: "Focus order preserves meaning and operability.",
    failsWhen: "Tab jumps randomly across columns.",
    productNote: "Header actions then main panels in DOM order.",
  },
  {
    id: "2.4.4",
    name: "Link Purpose (In Context)",
    level: "A",
    principle: "2 Operable",
    intent: "Link purpose clear from link text or context.",
    failsWhen: "“Click here” / “Spec” with no context.",
    productNote: "External spec links: include standard name in accessible name.",
  },
  {
    id: "2.4.5",
    name: "Multiple Ways",
    level: "AA",
    principle: "2 Operable",
    intent: "More than one way to locate pages (except process steps).",
    failsWhen: "Deep IA with only sequential links.",
    productNote: "Single-page app: in-page anchors (#keyboard-shortcuts, #a11y-standards) help.",
  },
  {
    id: "2.4.6",
    name: "Headings and Labels",
    level: "AA",
    principle: "2 Operable",
    intent: "Headings and labels describe topic or purpose.",
    failsWhen: "Vague “Section” headings; unlabeled inputs.",
    productNote: "Panel titles are descriptive; settings fields labeled.",
  },
  {
    id: "2.4.7",
    name: "Focus Visible",
    level: "AA",
    principle: "2 Operable",
    intent: "Keyboard focus indicator is visible.",
    failsWhen: "outline: none with no replacement.",
    productNote: ":focus-visible ring on controls.",
  },
  {
    id: "2.4.8",
    name: "Location",
    level: "AAA",
    principle: "2 Operable",
    intent: "User knows where they are in a set of pages (breadcrumbs, etc.).",
    failsWhen: "No orientation aid under AAA multi-page sites.",
    productNote: "AAA for multi-page; SPA shows run status in header.",
  },
  {
    id: "2.4.9",
    name: "Link Purpose (Link Only)",
    level: "AAA",
    principle: "2 Operable",
    intent: "Link purpose clear from link text alone.",
    failsWhen: "Ambiguous link text under AAA.",
    productNote: "AAA.",
  },
  {
    id: "2.4.10",
    name: "Section Headings",
    level: "AAA",
    principle: "2 Operable",
    intent: "Section headings organize content.",
    failsWhen: "Long pages with no headings under AAA.",
    productNote: "Panels use section headings.",
  },
  {
    id: "2.4.11",
    name: "Focus Not Obscured (Minimum)",
    level: "AA",
    principle: "2 Operable",
    intent: "Focused item is not entirely hidden by author-created content.",
    failsWhen: "Sticky footer/header fully covers focused control.",
    productNote: "Sticky header must not fully obscure focused fields.",
    wcag22Note: "New in WCAG 2.2.",
  },
  {
    id: "2.4.12",
    name: "Focus Not Obscured (Enhanced)",
    level: "AAA",
    principle: "2 Operable",
    intent: "Focused item is not hidden at all by author content.",
    failsWhen: "Any overlap of focus by sticky UI under AAA.",
    productNote: "AAA; new in 2.2.",
    wcag22Note: "New in WCAG 2.2.",
  },
  {
    id: "2.4.13",
    name: "Focus Appearance",
    level: "AAA",
    principle: "2 Operable",
    intent: "Focus indicator meets minimum area and contrast metrics.",
    failsWhen: "Hairline focus with low contrast under AAA.",
    productNote: "AAA; new in 2.2 — strengthen focus ring if claiming AAA.",
    wcag22Note: "New in WCAG 2.2.",
  },
  {
    id: "2.5.1",
    name: "Pointer Gestures",
    level: "A",
    principle: "2 Operable",
    intent: "Multipoint or path-based gestures have single-pointer alternative.",
    failsWhen: "Pinch-only zoom with no buttons.",
    productNote: "No complex gestures required.",
  },
  {
    id: "2.5.2",
    name: "Pointer Cancellation",
    level: "A",
    principle: "2 Operable",
    intent: "Down-event doesn’t complete action; or undo/abort available (up-event preferred).",
    failsWhen: "mousedown alone fires irreversible action.",
    productNote: "Use click/up handlers on buttons.",
  },
  {
    id: "2.5.3",
    name: "Label in Name",
    level: "A",
    principle: "2 Operable",
    intent: "Accessible name contains the visible label text.",
    failsWhen: "Visible “Submit” but aria-label “Send form now” without “Submit”.",
    productNote: "Keep aria-label consistent with visible button text.",
  },
  {
    id: "2.5.4",
    name: "Motion Actuation",
    level: "A",
    principle: "2 Operable",
    intent: "Device motion/gesture actuation has UI alternative and can be disabled.",
    failsWhen: "Shake-only actions.",
    productNote: "N/A for Control Room.",
  },
  {
    id: "2.5.5",
    name: "Target Size (Enhanced)",
    level: "AAA",
    principle: "2 Operable",
    intent: "Targets ≥ 44×44 CSS pixels (with exceptions).",
    failsWhen: "Tiny hit targets under AAA.",
    productNote: "Primary actions use h-11 (~44px).",
  },
  {
    id: "2.5.6",
    name: "Concurrent Input Mechanisms",
    level: "AAA",
    principle: "2 Operable",
    intent: "Content doesn’t restrict input to one modality unless essential.",
    failsWhen: "Touch-only while keyboard attached under AAA.",
    productNote: "AAA.",
  },
  {
    id: "2.5.7",
    name: "Dragging Movements",
    level: "AA",
    principle: "2 Operable",
    intent: "Dragging has a single-pointer non-drag alternative (unless essential).",
    failsWhen: "Reorder-only-by-drag lists.",
    productNote: "Prefer buttons over drag-only boards.",
    wcag22Note: "New in WCAG 2.2.",
  },
  {
    id: "2.5.8",
    name: "Target Size (Minimum)",
    level: "AA",
    principle: "2 Operable",
    intent: "Targets ≥ 24×24 CSS pixels (with spacing exceptions).",
    failsWhen: "Dense icon buttons under 24px without adequate spacing.",
    productNote:
      "Implemented: global min 24×24 on buttons/selects/checkboxes; primary actions h-11; hit-area-icon 44×44; audit enforces SC 2.5.8.",
    wcag22Note: "New in WCAG 2.2 (AA).",
  },

  // —— 3 Understandable ——
  {
    id: "3.1.1",
    name: "Language of Page",
    level: "A",
    principle: "3 Understandable",
    intent: "Default human language of page programmatically set (html lang).",
    failsWhen: "Missing lang attribute.",
    productNote: "html lang=en on root.",
  },
  {
    id: "3.1.2",
    name: "Language of Parts",
    level: "AA",
    principle: "3 Understandable",
    intent: "Language of phrases/passages set when it differs from page.",
    failsWhen: "Foreign quotes without lang.",
    productNote: "Mark non-English snippets if added.",
  },
  {
    id: "3.1.3",
    name: "Unusual Words",
    level: "AAA",
    principle: "3 Understandable",
    intent: "Definitions for idioms/jargon.",
    failsWhen: "Unexplained jargon under AAA.",
    productNote: "AAA — gloss agent terms if claiming AAA.",
  },
  {
    id: "3.1.4",
    name: "Abbreviations",
    level: "AAA",
    principle: "3 Understandable",
    intent: "Expansion/mechanism for abbreviations.",
    failsWhen: "P0/x402 unexplained under AAA.",
    productNote: "AAA.",
  },
  {
    id: "3.1.5",
    name: "Reading Level",
    level: "AAA",
    principle: "3 Understandable",
    intent: "Lower secondary reading level or supplemental content.",
    failsWhen: "Dense prose only under AAA.",
    productNote: "AAA.",
  },
  {
    id: "3.1.6",
    name: "Pronunciation",
    level: "AAA",
    principle: "3 Understandable",
    intent: "Pronunciation when meaning ambiguous without it.",
    failsWhen: "Ambiguous words with no aid under AAA.",
    productNote: "AAA.",
  },
  {
    id: "3.2.1",
    name: "On Focus",
    level: "A",
    principle: "3 Understandable",
    intent: "Focusing a component doesn’t initiate unexpected context change.",
    failsWhen: "Focus opens new page/submit.",
    productNote: "Focus shouldn’t auto-run board.",
  },
  {
    id: "3.2.2",
    name: "On Input",
    level: "A",
    principle: "3 Understandable",
    intent: "Changing setting doesn’t cause unexpected context change without warning.",
    failsWhen: "Changing select immediately navigates away.",
    productNote: "Filters update list in place — OK if expected.",
  },
  {
    id: "3.2.3",
    name: "Consistent Navigation",
    level: "AA",
    principle: "3 Understandable",
    intent: "Repeated navigation occurs in same relative order.",
    failsWhen: "Nav order changes across pages.",
    productNote: "Header controls stay consistent.",
  },
  {
    id: "3.2.4",
    name: "Consistent Identification",
    level: "AA",
    principle: "3 Understandable",
    intent: "Same functionality identified consistently.",
    failsWhen: "Same action labeled “Save” vs “Store” randomly.",
    productNote: "Keep “Live scout” / “Step” labels stable.",
  },
  {
    id: "3.2.5",
    name: "Change on Request",
    level: "AAA",
    principle: "3 Understandable",
    intent: "Context changes only on user request or controllable.",
    failsWhen: "Auto-refresh redirects under AAA.",
    productNote: "AAA.",
  },
  {
    id: "3.2.6",
    name: "Consistent Help",
    level: "A",
    principle: "3 Understandable",
    intent: "Help mechanisms (contact, chat, self-help, FAQ) appear in consistent order when repeated.",
    failsWhen: "Help entry point jumps around across pages.",
    productNote: "? help and shortcuts section stay in fixed places.",
    wcag22Note: "New in WCAG 2.2.",
  },
  {
    id: "3.3.1",
    name: "Error Identification",
    level: "A",
    principle: "3 Understandable",
    intent: "Input errors identified and described in text.",
    failsWhen: "Red border only, no message.",
    productNote: "Surface validation errors in text when forms ship.",
  },
  {
    id: "3.3.2",
    name: "Labels or Instructions",
    level: "A",
    principle: "3 Understandable",
    intent: "Labels/instructions when content requires input.",
    failsWhen: "Placeholder-only fields.",
    productNote: "Settings number fields have visible labels.",
  },
  {
    id: "3.3.3",
    name: "Error Suggestion",
    level: "AA",
    principle: "3 Understandable",
    intent: "Suggest corrections when known (unless security risk).",
    failsWhen: "“Invalid” without hint.",
    productNote: "Suggest ranges for BP settings on invalid numbers.",
  },
  {
    id: "3.3.4",
    name: "Error Prevention (Legal, Financial, Data)",
    level: "AA",
    principle: "3 Understandable",
    intent: "For legal/financial/data commits: reversible, checked, or confirmed.",
    failsWhen: "One-click irreversible purchase with no review.",
    productNote: "SHIP.1 requires explicit approval — good pattern.",
  },
  {
    id: "3.3.5",
    name: "Help",
    level: "AAA",
    principle: "3 Understandable",
    intent: "Context-sensitive help available.",
    failsWhen: "No field-level help under AAA.",
    productNote: "AAA.",
  },
  {
    id: "3.3.6",
    name: "Error Prevention (All)",
    level: "AAA",
    principle: "3 Understandable",
    intent: "For all submissions requiring user input: reverse/check/confirm.",
    failsWhen: "Any submit without prevention under AAA.",
    productNote: "AAA.",
  },
  {
    id: "3.3.7",
    name: "Redundant Entry",
    level: "A",
    principle: "3 Understandable",
    intent: "Don’t re-ask for info already provided in the same process (with exceptions).",
    failsWhen: "Multi-step forms retype same email/address.",
    productNote: "Persist run state; don’t re-prompt scout data.",
    wcag22Note: "New in WCAG 2.2.",
  },
  {
    id: "3.3.8",
    name: "Accessible Authentication (Minimum)",
    level: "AA",
    principle: "3 Understandable",
    intent: "Cognitive function test not required to authenticate unless alternative (e.g. object recognition with alternative, or copy-paste allowed for passwords).",
    failsWhen: "Puzzle-only login with no alternative; password managers blocked.",
    productNote: "Allow paste; avoid memory puzzles for auth.",
    wcag22Note: "New in WCAG 2.2.",
  },
  {
    id: "3.3.9",
    name: "Accessible Authentication (Enhanced)",
    level: "AAA",
    principle: "3 Understandable",
    intent: "No cognitive function test for authentication (stricter than 3.3.8).",
    failsWhen: "Any cognitive test under AAA auth.",
    productNote: "AAA; new in 2.2.",
    wcag22Note: "New in WCAG 2.2.",
  },

  // —— 4 Robust ——
  {
    id: "4.1.1",
    name: "Parsing",
    level: "A",
    principle: "4 Robust",
    intent: "Historically valid HTML nesting/ids; obsolete in 2.2 for most cases (removed as obsolete).",
    failsWhen: "N/A — criterion removed/obsoleted in WCAG 2.2.",
    productNote: "Still write valid DOM; criterion not used for 2.2 conformance the same way.",
    wcag22Note: "Removed (obsolete) in WCAG 2.2.",
  },
  {
    id: "4.1.2",
    name: "Name, Role, Value",
    level: "A",
    principle: "4 Robust",
    intent: "UI components expose name, role, state, value to AT; updates available.",
    failsWhen: "Custom div-buttons without role/name; dialogs unlabeled.",
    productNote: "Native buttons; role=dialog + aria-label on overlays.",
  },
  {
    id: "4.1.3",
    name: "Status Messages",
    level: "AA",
    principle: "4 Robust",
    intent: "Status messages can be presented by AT without receiving focus (aria-live/role=status).",
    failsWhen: "Toasts only visual; no live region.",
    productNote: "aria-live region + consider toast announcements.",
  },
];

export const WCAG22_NEW_OR_NOTABLE = WCAG22_CRITERIA.filter((c) => c.wcag22Note);

export function groupByPrinciple(list: Wcag22Criterion[] = WCAG22_CRITERIA) {
  const order: WcagPrinciple[] = [
    "1 Perceivable",
    "2 Operable",
    "3 Understandable",
    "4 Robust",
  ];
  return order.map((principle) => ({
    principle,
    items: list.filter((c) => c.principle === principle),
  }));
}

export const WCAG22_COUNTS = {
  total: WCAG22_CRITERIA.filter((c) => c.id !== "4.1.1").length,
  A: WCAG22_CRITERIA.filter((c) => c.level === "A" && c.id !== "4.1.1").length,
  AA: WCAG22_CRITERIA.filter((c) => c.level === "AA").length,
  AAA: WCAG22_CRITERIA.filter((c) => c.level === "AAA").length,
  newIn22: WCAG22_NEW_OR_NOTABLE.length,
};
