/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as LabInteropRouteImport } from './routes/lab/interop'
import { Route as LabLoadersRouteImport } from './routes/lab/loaders'
import { Route as LabRouterRouteImport } from './routes/lab/router'
import { Route as LabSettlementRouteImport } from './routes/lab/settlement'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace/index'
import { Route as MarketplaceAgentEconomyRouteImport } from './routes/marketplace/agent-economy'
import { Route as MarketplaceCatalogRouteImport } from './routes/marketplace/catalog'
import { Route as MarketplaceCheckoutRouteImport } from './routes/marketplace/checkout'
import { Route as MarketplaceDemandRouteImport } from './routes/marketplace/demand'
import { Route as MarketplaceLadderRouteImport } from './routes/marketplace/ladder'
import { Route as MarketplaceProductRouteImport } from './routes/marketplace/product'
import { Route as MarketplaceRailsRouteImport } from './routes/marketplace/rails'
import { Route as MarketplaceSdkRouteImport } from './routes/marketplace/sdk'
import { Route as MarketplaceSellRouteImport } from './routes/marketplace/sell'
import { Route as MarketplaceX402RouteImport } from './routes/marketplace/x402'
import { Route as OpsIndexRouteImport } from './routes/ops/index'
import { Route as OpsBoardRouteImport } from './routes/ops/board'
import { Route as OpsHealthRouteImport } from './routes/ops/health'
import { Route as OpsScoutRouteImport } from './routes/ops/scout'
import { Route as SkillsIndexRouteImport } from './routes/skills/index'
import { Route as SkillsPackIdRouteImport } from './routes/skills/$packId'
import { Route as MarketplaceSkillSkillIdRouteImport } from './routes/marketplace/skill.$skillId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const LabInteropRoute = LabInteropRouteImport.update({
  id: '/lab/interop',
  path: '/lab/interop',
  getParentRoute: () => rootRouteImport,
} as any)
const LabLoadersRoute = LabLoadersRouteImport.update({
  id: '/lab/loaders',
  path: '/lab/loaders',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRouterRoute = LabRouterRouteImport.update({
  id: '/lab/router',
  path: '/lab/router',
  getParentRoute: () => rootRouteImport,
} as any)
const LabSettlementRoute = LabSettlementRouteImport.update({
  id: '/lab/settlement',
  path: '/lab/settlement',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceAgentEconomyRoute = MarketplaceAgentEconomyRouteImport.update({
  id: '/agent-economy',
  path: '/agent-economy',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceCatalogRoute = MarketplaceCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceCheckoutRoute = MarketplaceCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceDemandRoute = MarketplaceDemandRouteImport.update({
  id: '/demand',
  path: '/demand',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceLadderRoute = MarketplaceLadderRouteImport.update({
  id: '/ladder',
  path: '/ladder',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceProductRoute = MarketplaceProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceRailsRoute = MarketplaceRailsRouteImport.update({
  id: '/rails',
  path: '/rails',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceSdkRoute = MarketplaceSdkRouteImport.update({
  id: '/sdk',
  path: '/sdk',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceSellRoute = MarketplaceSellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceX402Route = MarketplaceX402RouteImport.update({
  id: '/x402',
  path: '/x402',
  getParentRoute: () => MarketplaceRoute,
} as any)
const OpsIndexRoute = OpsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsRoute,
} as any)
const OpsBoardRoute = OpsBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => OpsRoute,
} as any)
const OpsHealthRoute = OpsHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => OpsRoute,
} as any)
const OpsScoutRoute = OpsScoutRouteImport.update({
  id: '/scout',
  path: '/scout',
  getParentRoute: () => OpsRoute,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SkillsRoute,
} as any)
const SkillsPackIdRoute = SkillsPackIdRouteImport.update({
  id: '/$packId',
  path: '/$packId',
  getParentRoute: () => SkillsRoute,
} as any)
const MarketplaceSkillSkillIdRoute = MarketplaceSkillSkillIdRouteImport.update({
  id: '/skill/$skillId',
  path: '/skill/$skillId',
  getParentRoute: () => MarketplaceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/ops': typeof OpsRouteWithChildren
  '/skills': typeof SkillsRouteWithChildren
  '/lab/interop': typeof LabInteropRoute
  '/lab/loaders': typeof LabLoadersRoute
  '/lab/router': typeof LabRouterRoute
  '/lab/settlement': typeof LabSettlementRoute
  '/marketplace/agent-economy': typeof MarketplaceAgentEconomyRoute
  '/marketplace/catalog': typeof MarketplaceCatalogRoute
  '/marketplace/checkout': typeof MarketplaceCheckoutRoute
  '/marketplace/demand': typeof MarketplaceDemandRoute
  '/marketplace/ladder': typeof MarketplaceLadderRoute
  '/marketplace/product': typeof MarketplaceProductRoute
  '/marketplace/rails': typeof MarketplaceRailsRoute
  '/marketplace/sdk': typeof MarketplaceSdkRoute
  '/marketplace/sell': typeof MarketplaceSellRoute
  '/marketplace/x402': typeof MarketplaceX402Route
  '/ops/board': typeof OpsBoardRoute
  '/ops/health': typeof OpsHealthRoute
  '/ops/scout': typeof OpsScoutRoute
  '/skills/$packId': typeof SkillsPackIdRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/ops/': typeof OpsIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/marketplace/skill/$skillId': typeof MarketplaceSkillSkillIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lab/interop': typeof LabInteropRoute
  '/lab/loaders': typeof LabLoadersRoute
  '/lab/router': typeof LabRouterRoute
  '/lab/settlement': typeof LabSettlementRoute
  '/marketplace/agent-economy': typeof MarketplaceAgentEconomyRoute
  '/marketplace/catalog': typeof MarketplaceCatalogRoute
  '/marketplace/checkout': typeof MarketplaceCheckoutRoute
  '/marketplace/demand': typeof MarketplaceDemandRoute
  '/marketplace/ladder': typeof MarketplaceLadderRoute
  '/marketplace/product': typeof MarketplaceProductRoute
  '/marketplace/rails': typeof MarketplaceRailsRoute
  '/marketplace/sdk': typeof MarketplaceSdkRoute
  '/marketplace/sell': typeof MarketplaceSellRoute
  '/marketplace/x402': typeof MarketplaceX402Route
  '/ops/board': typeof OpsBoardRoute
  '/ops/health': typeof OpsHealthRoute
  '/ops/scout': typeof OpsScoutRoute
  '/skills/$packId': typeof SkillsPackIdRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/ops': typeof OpsIndexRoute
  '/skills': typeof SkillsIndexRoute
  '/marketplace/skill/$skillId': typeof MarketplaceSkillSkillIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/ops': typeof OpsRouteWithChildren
  '/skills': typeof SkillsRouteWithChildren
  '/lab/interop': typeof LabInteropRoute
  '/lab/loaders': typeof LabLoadersRoute
  '/lab/router': typeof LabRouterRoute
  '/lab/settlement': typeof LabSettlementRoute
  '/marketplace/agent-economy': typeof MarketplaceAgentEconomyRoute
  '/marketplace/catalog': typeof MarketplaceCatalogRoute
  '/marketplace/checkout': typeof MarketplaceCheckoutRoute
  '/marketplace/demand': typeof MarketplaceDemandRoute
  '/marketplace/ladder': typeof MarketplaceLadderRoute
  '/marketplace/product': typeof MarketplaceProductRoute
  '/marketplace/rails': typeof MarketplaceRailsRoute
  '/marketplace/sdk': typeof MarketplaceSdkRoute
  '/marketplace/sell': typeof MarketplaceSellRoute
  '/marketplace/x402': typeof MarketplaceX402Route
  '/ops/board': typeof OpsBoardRoute
  '/ops/health': typeof OpsHealthRoute
  '/ops/scout': typeof OpsScoutRoute
  '/skills/$packId': typeof SkillsPackIdRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/ops/': typeof OpsIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/marketplace/skill/$skillId': typeof MarketplaceSkillSkillIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/marketplace'
    | '/ops'
    | '/skills'
    | '/lab/interop'
    | '/lab/loaders'
    | '/lab/router'
    | '/lab/settlement'
    | '/marketplace/agent-economy'
    | '/marketplace/catalog'
    | '/marketplace/checkout'
    | '/marketplace/demand'
    | '/marketplace/ladder'
    | '/marketplace/product'
    | '/marketplace/rails'
    | '/marketplace/sdk'
    | '/marketplace/sell'
    | '/marketplace/x402'
    | '/ops/board'
    | '/ops/health'
    | '/ops/scout'
    | '/skills/$packId'
    | '/marketplace/'
    | '/ops/'
    | '/skills/'
    | '/marketplace/skill/$skillId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lab/interop'
    | '/lab/loaders'
    | '/lab/router'
    | '/lab/settlement'
    | '/marketplace/agent-economy'
    | '/marketplace/catalog'
    | '/marketplace/checkout'
    | '/marketplace/demand'
    | '/marketplace/ladder'
    | '/marketplace/product'
    | '/marketplace/rails'
    | '/marketplace/sdk'
    | '/marketplace/sell'
    | '/marketplace/x402'
    | '/ops/board'
    | '/ops/health'
    | '/ops/scout'
    | '/skills/$packId'
    | '/marketplace'
    | '/ops'
    | '/skills'
    | '/marketplace/skill/$skillId'
  id:
    | '__root__'
    | '/'
    | '/marketplace'
    | '/ops'
    | '/skills'
    | '/lab/interop'
    | '/lab/loaders'
    | '/lab/router'
    | '/lab/settlement'
    | '/marketplace/agent-economy'
    | '/marketplace/catalog'
    | '/marketplace/checkout'
    | '/marketplace/demand'
    | '/marketplace/ladder'
    | '/marketplace/product'
    | '/marketplace/rails'
    | '/marketplace/sdk'
    | '/marketplace/sell'
    | '/marketplace/x402'
    | '/ops/board'
    | '/ops/health'
    | '/ops/scout'
    | '/skills/$packId'
    | '/marketplace/'
    | '/ops/'
    | '/skills/'
    | '/marketplace/skill/$skillId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  OpsRoute: typeof OpsRouteWithChildren
  SkillsRoute: typeof SkillsRouteWithChildren
  LabInteropRoute: typeof LabInteropRoute
  LabLoadersRoute: typeof LabLoadersRoute
  LabRouterRoute: typeof LabRouterRoute
  LabSettlementRoute: typeof LabSettlementRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/interop': {
      id: '/lab/interop'
      path: '/lab/interop'
      fullPath: '/lab/interop'
      preLoaderRoute: typeof LabInteropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/loaders': {
      id: '/lab/loaders'
      path: '/lab/loaders'
      fullPath: '/lab/loaders'
      preLoaderRoute: typeof LabLoadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/router': {
      id: '/lab/router'
      path: '/lab/router'
      fullPath: '/lab/router'
      preLoaderRoute: typeof LabRouterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/settlement': {
      id: '/lab/settlement'
      path: '/lab/settlement'
      fullPath: '/lab/settlement'
      preLoaderRoute: typeof LabSettlementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/agent-economy': {
      id: '/marketplace/agent-economy'
      path: '/agent-economy'
      fullPath: '/marketplace/agent-economy'
      preLoaderRoute: typeof MarketplaceAgentEconomyRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/catalog': {
      id: '/marketplace/catalog'
      path: '/catalog'
      fullPath: '/marketplace/catalog'
      preLoaderRoute: typeof MarketplaceCatalogRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/checkout': {
      id: '/marketplace/checkout'
      path: '/checkout'
      fullPath: '/marketplace/checkout'
      preLoaderRoute: typeof MarketplaceCheckoutRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/demand': {
      id: '/marketplace/demand'
      path: '/demand'
      fullPath: '/marketplace/demand'
      preLoaderRoute: typeof MarketplaceDemandRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/ladder': {
      id: '/marketplace/ladder'
      path: '/ladder'
      fullPath: '/marketplace/ladder'
      preLoaderRoute: typeof MarketplaceLadderRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/product': {
      id: '/marketplace/product'
      path: '/product'
      fullPath: '/marketplace/product'
      preLoaderRoute: typeof MarketplaceProductRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/rails': {
      id: '/marketplace/rails'
      path: '/rails'
      fullPath: '/marketplace/rails'
      preLoaderRoute: typeof MarketplaceRailsRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/sdk': {
      id: '/marketplace/sdk'
      path: '/sdk'
      fullPath: '/marketplace/sdk'
      preLoaderRoute: typeof MarketplaceSdkRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/sell': {
      id: '/marketplace/sell'
      path: '/sell'
      fullPath: '/marketplace/sell'
      preLoaderRoute: typeof MarketplaceSellRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/x402': {
      id: '/marketplace/x402'
      path: '/x402'
      fullPath: '/marketplace/x402'
      preLoaderRoute: typeof MarketplaceX402RouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/ops/': {
      id: '/ops/'
      path: '/'
      fullPath: '/ops/'
      preLoaderRoute: typeof OpsIndexRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/board': {
      id: '/ops/board'
      path: '/board'
      fullPath: '/ops/board'
      preLoaderRoute: typeof OpsBoardRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/health': {
      id: '/ops/health'
      path: '/health'
      fullPath: '/ops/health'
      preLoaderRoute: typeof OpsHealthRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/scout': {
      id: '/ops/scout'
      path: '/scout'
      fullPath: '/ops/scout'
      preLoaderRoute: typeof OpsScoutRouteImport
      parentRoute: typeof OpsRoute
    }
    '/skills/': {
      id: '/skills/'
      path: '/'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof SkillsRoute
    }
    '/skills/$packId': {
      id: '/skills/$packId'
      path: '/$packId'
      fullPath: '/skills/$packId'
      preLoaderRoute: typeof SkillsPackIdRouteImport
      parentRoute: typeof SkillsRoute
    }
    '/marketplace/skill/$skillId': {
      id: '/marketplace/skill/$skillId'
      path: '/skill/$skillId'
      fullPath: '/marketplace/skill/$skillId'
      preLoaderRoute: typeof MarketplaceSkillSkillIdRouteImport
      parentRoute: typeof MarketplaceRoute
    }
  }
}

interface MarketplaceRouteChildren {
  MarketplaceAgentEconomyRoute: typeof MarketplaceAgentEconomyRoute
  MarketplaceCatalogRoute: typeof MarketplaceCatalogRoute
  MarketplaceCheckoutRoute: typeof MarketplaceCheckoutRoute
  MarketplaceDemandRoute: typeof MarketplaceDemandRoute
  MarketplaceLadderRoute: typeof MarketplaceLadderRoute
  MarketplaceProductRoute: typeof MarketplaceProductRoute
  MarketplaceRailsRoute: typeof MarketplaceRailsRoute
  MarketplaceSdkRoute: typeof MarketplaceSdkRoute
  MarketplaceSellRoute: typeof MarketplaceSellRoute
  MarketplaceX402Route: typeof MarketplaceX402Route
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
  MarketplaceSkillSkillIdRoute: typeof MarketplaceSkillSkillIdRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceAgentEconomyRoute: MarketplaceAgentEconomyRoute,
  MarketplaceCatalogRoute: MarketplaceCatalogRoute,
  MarketplaceCheckoutRoute: MarketplaceCheckoutRoute,
  MarketplaceDemandRoute: MarketplaceDemandRoute,
  MarketplaceLadderRoute: MarketplaceLadderRoute,
  MarketplaceProductRoute: MarketplaceProductRoute,
  MarketplaceRailsRoute: MarketplaceRailsRoute,
  MarketplaceSdkRoute: MarketplaceSdkRoute,
  MarketplaceSellRoute: MarketplaceSellRoute,
  MarketplaceX402Route: MarketplaceX402Route,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
  MarketplaceSkillSkillIdRoute: MarketplaceSkillSkillIdRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

interface OpsRouteChildren {
  OpsBoardRoute: typeof OpsBoardRoute
  OpsHealthRoute: typeof OpsHealthRoute
  OpsScoutRoute: typeof OpsScoutRoute
  OpsIndexRoute: typeof OpsIndexRoute
}

const OpsRouteChildren: OpsRouteChildren = {
  OpsBoardRoute: OpsBoardRoute,
  OpsHealthRoute: OpsHealthRoute,
  OpsScoutRoute: OpsScoutRoute,
  OpsIndexRoute: OpsIndexRoute,
}

const OpsRouteWithChildren = OpsRoute._addFileChildren(OpsRouteChildren)

interface SkillsRouteChildren {
  SkillsPackIdRoute: typeof SkillsPackIdRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
}

const SkillsRouteChildren: SkillsRouteChildren = {
  SkillsPackIdRoute: SkillsPackIdRoute,
  SkillsIndexRoute: SkillsIndexRoute,
}

const SkillsRouteWithChildren =
  SkillsRoute._addFileChildren(SkillsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  OpsRoute: OpsRouteWithChildren,
  SkillsRoute: SkillsRouteWithChildren,
  LabInteropRoute: LabInteropRoute,
  LabLoadersRoute: LabLoadersRoute,
  LabRouterRoute: LabRouterRoute,
  LabSettlementRoute: LabSettlementRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
